### ISSUE TITLE
os.environ["HOME"] is unsupported on Windows

### ISSUE THREAD

**Issue by nesclass** [airtai/fastkafka#291]
Encountered a `KeyError` related to the `HOME` environment variable while attempting to run FastKafka on Windows platform.

```bash
(stats-bot-py3.11) PS C:\Users\nesclass\Workflow\griefyou\stats-bot> fastkafka
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nesclass\AppData\Local\pypoetry\Cache\virtualenvs\stats-bot-aYPg2ZVp-py3.11\Scripts\fastkafka.exe\__main__.py", line 4, in <module>
...
  File "C:\Users\nesclass\AppData\Local\pypoetry\Cache\virtualenvs\stats-bot-aYPg2ZVp-py3.11\Lib\site-packages\fastkafka\_components\docs_dependencies.py", line 55, in <module>    
    local_path = Path(os.environ["HOME"]) / ".local"
                      ~~~~~~~~~~^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'HOME'
```

One of the potential solutions for this problem is to use `USERPROFILE` as a platform-dependent alternative for provided variable.

Also, you can get home folder using [os.path](https://docs.python.org/3/library/os.path.html) as follows:

```python
local_path = Path(os.path.expanduser("~")) / ".local"
```

**Comment by Sternakt** [comment]
Closing it as it's a duplicate, referenced in #130
