### ISSUE TITLE
RequestTimedOutError in send

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastkafka#432]

**Comment by davorrunje** [comment]
3-07-10 04:39:58.740 [ERROR] asyncio: Future exception was never retrieved
future: <Future finished exception=RequestTimedOutError()>
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/aiokafka/producer/sender.py", line 716, in do
    response = await self._client.send(node_id, request)
  File "/root/.local/lib/python3.8/site-packages/aiokafka/client.py", line 512, in send
    raise RequestTimedOutError()
kafka.errors.RequestTimedOutError: [Error 7] RequestTimedOutError
